### ISSUE TITLE
Package throws runtime error

### ISSUE THREAD

**Issue by dVoidMan** [nschairer/keyboard_height_plugin#4]
The package throws this error at runtime:

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel keyboardHeightEventChannel:
MissingPluginException(No implementation found for method listen on channel keyboardHeightEventChannel)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:652:9)
<asynchronous suspension>
====================================================================================================

I even cloned the repo and re-ran. Same result.

Please what could be wrong?

**Comment by dVoidMan** [comment]
It now works!

It worked after I re-ran my application (hot re-load and hot-restart may not work)
